[versions]
agp = "9.0.0"
androidx-test = "1.7.0"
kotlin = "2.3.10"
starter = "0.94.0"

[plugins]
agp-library = { id = "com.android.library", version.ref = "agp" }
binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.18.1" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.36.0" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
starter-library-kotlin = { id = "com.starter.library.kotlin", version.ref = "starter" }

[libraries]
androidx-annotation = "androidx.annotation:annotation:1.9.1"
androidx-test-orchestrator = "androidx.test:orchestrator:1.6.1"
androidx-test-rules = { module = "androidx.test:rules", version = "1.7.0" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-truth = "androidx.test.ext:junit:1.3.0"
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
desugarJdkLibs = "com.android.tools:desugar_jdk_libs:2.1.5"
javapoet = "com.squareup:javapoet:1.13.0"
junit = "junit:junit:4.13.2"
kgp = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kgp-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
kotlinpoet = "com.squareup:kotlinpoet:2.2.0"
okio = "com.squareup.okio:okio:3.16.4"
truth = "com.google.truth:truth:1.4.5"
zipflinger = { module = "com.android:zipflinger", version.ref = "agp" }
