[versions]
maven-kotlin = "2.3.10"
google-agp = "9.0.1"
androidx-test = "1.7.0"
java-target = "11"

[libraries]
androidx-annotation = "androidx.annotation:annotation:1.9.1"
androidx-test-orchestrator = "androidx.test:orchestrator:1.6.1"
androidx-test-rules = { module = "androidx.test:rules", version = "1.7.0" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-truth = "androidx.test.ext:junit:1.3.0"
desugarJdkLibs = "com.android.tools:desugar_jdk_libs:2.1.5"
junit = "junit:junit:4.13.2"
truth = "com.google.truth:truth:1.4.5"
okio = "com.squareup.okio:okio:3.16.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "google-agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "maven-kotlin" }
