name: Build Project

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: 'ci-${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

env:
  # Test on API 30 because that's the first version with ATDs
  API_LEVEL: '30'
  AVD_TARGET: 'aosp_atd'

jobs:
  build:
    name: ${{ matrix.job }} / AGP ${{ matrix.agp }} / OS ${{ matrix.os }}
    # Use macOS for emulator hardware acceleration
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false # We want to see all results
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
        agp: [ '8.5.0', 'stable', 'alpha' ]
        job: [ 'instrumentation', 'plugin' ]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version-file: .java-version

      - uses: gradle/actions/wrapper-validation@v5

      - id: agp-version-finder
        uses: usefulness/agp-version-finder-action@v1
        with:
          version-to-resolve: ${{ matrix.agp }}

      - name: Set AGP Version as ENV
        run: echo "DEP_OVERRIDE_agp=${{ steps.agp-version-finder.outputs.resolved-version }}" >> $GITHUB_ENV

      - uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew projectCodestyle --scan

      - name: Test plugin
        id: gradle
        if: matrix.job == 'plugin'
        run: ./gradlew -p keeper-gradle-plugin check

      - run: ./gradlew publishToMavenLocal
        if: matrix.job == 'plugin'

      - run: ./gradlew publishPlugins --dry-run
        if: matrix.job == 'plugin'

      - run: git diff --exit-code

      - name: Assemble instrumentation tests
        id: gradle-assemble-instrumentation
        if: matrix.job == 'instrumentation'
        run: ./gradlew :sample:minifyExternalStagingWithR8 validateL8 --stacktrace

      - name: Enable KVM group perms
        if: matrix.job == 'instrumentation' && matrix.os == 'ubuntu-latest'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm   

      - name: Run instrumentation tests
        if: matrix.job == 'instrumentation' && matrix.os == 'ubuntu-latest'
        id: gradle-instrumentation-fork
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.API_LEVEL }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          disable-spellchecker: true
          disk-size: 6000M
          heap-size: 600M
          target: 'aosp_atd'
          channel: canary # Necessary for ATDs
          script: |
            adb uninstall com.slack.keeper.sample || true
            adb uninstall com.slack.keeper.sample.androidTest || true
            
            # Now proceed, with much of the build being cached up to this point
            echo "Running instrumentation tests"
            ./gradlew connectedExternalStagingAndroidTest --stacktrace
            
            adb uninstall com.slack.keeper.sample || true
            adb uninstall com.slack.keeper.sample.androidTest || true

      - name: (Fail-only) Upload the build reports
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: error-report-${{ matrix.job }}-${{ matrix.agp }}-${{ matrix.os }}
          path: |
            keeper-gradle-plugin/build/reports
            sample/build/reports
